# Generated by Django 4.0.6 on 2023-03-21 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_kitap_acikama_alter_dergi_foto_alter_kitap_foto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siir',
            name='foto',
        ),
        migrations.AddField(
            model_name='siir',
            name='siir',
            field=models.CharField(default='a', max_length=512),
            preserve_default=False,
        ),
    ]
