# Generated by Django 4.1.3 on 2023-04-25 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('down_votes', models.IntegerField(default=0)),
                ('up_votes', models.IntegerField(default=0)),
                ('interest_rate', models.FloatField(default=0, editable=False)),
                ('author_name', models.CharField(max_length=30, verbose_name='Kullanıcı Adı')),
                ('content', models.TextField(max_length=1000, verbose_name='Yorum İçeriği')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.CharField(blank=True, choices=[(None, 'None'), ('phasenull', 'phasenull'), ('admin', 'admin')], default=None, max_length=30, null=True, verbose_name='Onaylayan Yetkili')),
                ('hide_name', models.BooleanField(default=False, verbose_name='Yazar İsmini Gizle')),
                ('spoilers', models.BooleanField(default=False, verbose_name='Mesaj Spoiler İçeriyor')),
                ('author_ip', models.CharField(editable=False, max_length=30)),
                ('author_headers', models.CharField(default='?', editable=False, max_length=1000)),
                ('author_id', models.CharField(default=-1, editable=False, max_length=3, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateField()),
                ('image', models.ImageField(default='foto/noimage.png', upload_to='foto')),
                ('type', models.CharField(choices=[('writer', 'Yazar'), ('publisher', 'Yayımcı')], default='writer', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LiteratureObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('down_votes', models.IntegerField(default=0)),
                ('up_votes', models.IntegerField(default=0)),
                ('interest_rate', models.FloatField(default=0, editable=False)),
                ('name', models.CharField(max_length=255, verbose_name='İsim')),
                ('image', models.ImageField(default='foto/noimage.png', upload_to='foto', verbose_name='Fotoğraf')),
                ('url', models.URLField(verbose_name='Esere ait link')),
                ('content', models.TextField(max_length=1000, verbose_name='İçerik')),
                ('type', models.TextField(choices=[('book', 'Kitap'), ('magazine', 'Dergi'), ('poem', 'Şiir')], verbose_name='Tür')),
                ('creator', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='index.creator', verbose_name='Yazar / Yayıncı')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_adress', models.GenericIPAddressField(default='0.0.0.0')),
                ('value', models.IntegerField(default=0)),
                ('parent_object_type', models.TextField(choices=[('a', 'Yorum'), ('b', 'Eser')], default='a')),
                ('parent_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='index.comment')),
                ('parent_literature_object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='index.literatureobject')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='parent_object',
            field=models.ForeignKey(default=0, editable=False, on_delete=django.db.models.deletion.CASCADE, to='index.literatureobject', verbose_name='Yorum Yapılan Eser'),
        ),
    ]
