# Generated by Django 4.1.3 on 2023-04-08 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_vote2_delete_vote'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_adress', models.GenericIPAddressField(default='0.0.0.0')),
                ('value', models.IntegerField(default=0)),
                ('parent_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='index.comment')),
                ('parent_literature_object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='index.literatureobject')),
            ],
        ),
        migrations.DeleteModel(
            name='Vote2',
        ),
    ]
