# Generated by Django 4.0.6 on 2023-03-15 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_yazar'),
    ]

    operations = [
        migrations.AddField(
            model_name='dergi',
            name='foto',
            field=models.ImageField(null=True, upload_to='foto'),
        ),
        migrations.AddField(
            model_name='kitap',
            name='foto',
            field=models.ImageField(null=True, upload_to='foto'),
        ),
        migrations.AddField(
            model_name='siir',
            name='foto',
            field=models.ImageField(null=True, upload_to='foto'),
        ),
        migrations.AddField(
            model_name='yazar',
            name='foto',
            field=models.ImageField(null=True, upload_to='foto'),
        ),
    ]
