# Generated by Django 4.0.6 on 2023-03-18 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_dergi_foto_kitap_foto_siir_foto_yazar_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitap',
            name='acikama',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='dergi',
            name='foto',
            field=models.ImageField(default='foto/noimage.png', upload_to='foto'),
        ),
        migrations.AlterField(
            model_name='kitap',
            name='foto',
            field=models.ImageField(default='foto/noimage.png', upload_to='foto'),
        ),
        migrations.AlterField(
            model_name='siir',
            name='foto',
            field=models.ImageField(default='foto/noimage.png', upload_to='foto'),
        ),
        migrations.AlterField(
            model_name='yazar',
            name='foto',
            field=models.ImageField(default='foto/noimage.png', upload_to='foto'),
        ),
    ]
