# Generated by Django 4.1.3 on 2023-04-08 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_vote_parent_object_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='approved_by',
            field=models.CharField(blank=True, choices=[(None, 'None'), ('phasenull', 'phasenull'), ('admin', 'admin')], default=None, max_length=30, null=True, verbose_name='Onaylayan Yetkili'),
        ),
    ]
