# Generated by Django 4.1.3 on 2023-04-08 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_alter_comment_approved_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='interest_rate',
            field=models.FloatField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='literatureobject',
            name='interest_rate',
            field=models.FloatField(default=0, editable=False),
        ),
    ]
