# Generated by Django 4.0.6 on 2023-03-21 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_alter_siir_siir'),
    ]

    operations = [
        migrations.AddField(
            model_name='dergi',
            name='url',
            field=models.URLField(default='a'),
            preserve_default=False,
        ),
    ]
