# Generated by Django 4.1.3 on 2023-04-16 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_rename_message_comment_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateField(auto_created=True, editable=False),
        ),
    ]
