# Generated by Django 4.1.7 on 2023-03-29 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_dergi_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitap',
            name='key_name',
            field=models.CharField(default='None', max_length=255),
        ),
    ]
