# Generated by Django 4.1.7 on 2023-04-05 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_remove_kitap_key_name_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='parent',
            field=models.IntegerField(default=0, editable=False, verbose_name='Yorum Yapılan Eser Numarası'),
        ),
    ]
