# Generated by Django 4.1.7 on 2023-04-05 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0010_alter_comment_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='approved_by',
            field=models.CharField(default='Bilinmiyor', max_length=30, verbose_name='Onaylayan Yetkili'),
        ),
        migrations.AddField(
            model_name='comment',
            name='author_headers',
            field=models.CharField(default='?', max_length=1000),
        ),
        migrations.AddField(
            model_name='comment',
            name='author_ip',
            field=models.CharField(default='?', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='hide_name',
            field=models.BooleanField(default=False, editable=False, verbose_name='İsmi Gizle'),
        ),
        migrations.AddField(
            model_name='comment',
            name='spoilers',
            field=models.BooleanField(default=False, verbose_name='Spoiler'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='parent',
            field=models.IntegerField(default=0, verbose_name='Yorum Yapılan Eser Numarası'),
        ),
    ]
