# Generated by Django 4.1.3 on 2023-04-06 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0011_comment_approved_by_comment_author_headers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='author_id',
            field=models.IntegerField(default=-1, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author_headers',
            field=models.CharField(default='?', editable=False, max_length=1000),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author_ip',
            field=models.CharField(editable=False, max_length=30),
        ),
        migrations.AlterField(
            model_name='comment',
            name='hide_name',
            field=models.BooleanField(default=False, verbose_name='Yazar İsmini Gizle'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='parent',
            field=models.IntegerField(default=0, editable=False, verbose_name='Yorum Yapılan Eser Numarası'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='spoilers',
            field=models.BooleanField(default=False, verbose_name='Mesaj Spoiler İçeriyor'),
        ),
    ]
