# Generated by Django 4.1.3 on 2023-04-06 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0012_comment_author_id_alter_comment_author_headers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author_id',
            field=models.CharField(default=-1, editable=False, max_length=3, null=True),
        ),
    ]
