# Generated by Django 4.1.3 on 2023-04-07 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0014_vote_comment_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='vote_count',
            field=models.JSONField(default={'down': 0, 'up': 0}),
        ),
        migrations.AlterField(
            model_name='comment',
            name='votes',
            field=models.ManyToManyField(default=None, to='index.vote'),
        ),
    ]
