# Generated by Django 4.1.3 on 2023-04-07 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0015_comment_vote_count_alter_comment_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='ip_adress',
            field=models.GenericIPAddressField(default='0.0.0.0'),
        ),
    ]
