# Generated by Django 4.1.3 on 2023-04-07 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0016_vote_ip_adress'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='DOWN',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vote',
            name='UP',
            field=models.IntegerField(default=0),
        ),
    ]
