# Generated by Django 4.1.3 on 2023-04-07 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0018_remove_comment_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='votes',
            field=models.ManyToManyField(default=None, to='index.vote'),
        ),
    ]
