# Generated by Django 4.1.3 on 2023-04-07 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0019_comment_votes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='vote_count',
        ),
        migrations.AddField(
            model_name='comment',
            name='down_votes',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='comment',
            name='up_votes',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='message',
            field=models.TextField(max_length=1000, verbose_name='Yorum İçeriği'),
        ),
    ]
