# Generated by Django 4.1.3 on 2023-04-07 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0020_remove_comment_vote_count_comment_down_votes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='DOWN',
            new_name='value',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='UP',
        ),
        migrations.AlterField(
            model_name='comment',
            name='votes',
            field=models.ManyToManyField(default=None, editable=False, to='index.vote'),
        ),
    ]
