# Generated by Django 4.1.3 on 2023-04-07 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0021_rename_down_vote_value_remove_vote_up_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='down_votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='comment',
            name='up_votes',
            field=models.IntegerField(default=0),
        ),
    ]
