# Generated by Django 4.1.3 on 2023-04-07 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0022_alter_comment_down_votes_alter_comment_up_votes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='votes',
        ),
        migrations.AddField(
            model_name='vote',
            name='parent_comment',
            field=models.ManyToManyField(to='index.comment'),
        ),
    ]
