# Generated by Django 4.1.3 on 2023-04-07 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0023_remove_comment_votes_vote_parent_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='parent_comment',
        ),
        migrations.AddField(
            model_name='vote',
            name='parent_comment',
            field=models.ForeignKey(editable=False, null=django.db.models.deletion.CASCADE, on_delete=django.db.models.deletion.CASCADE, to='index.comment'),
            preserve_default=django.db.models.deletion.CASCADE,
        ),
    ]
