# Generated by Django 4.1.3 on 2023-04-07 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0024_remove_vote_parent_comment_vote_parent_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='parent',
            new_name='parent_object',
        ),
        migrations.AlterField(
            model_name='vote',
            name='parent_comment',
            field=models.ForeignKey(null=django.db.models.deletion.CASCADE, on_delete=django.db.models.deletion.CASCADE, to='index.comment'),
        ),
    ]
