# Generated by Django 4.1.3 on 2023-04-07 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0025_rename_parent_comment_parent_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateField()),
                ('image', models.ImageField(default='foto/noimage.png', upload_to='foto')),
            ],
        ),
        migrations.CreateModel(
            name='LiteratureObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(default='foto/noimage.png', upload_to='foto')),
                ('url', models.URLField()),
                ('content', models.TextField(max_length=1000)),
                ('type', models.TextField(choices=[('1', 'a')])),
                ('creator', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='index.creator')),
            ],
        ),
        migrations.DeleteModel(
            name='Dergi',
        ),
        migrations.DeleteModel(
            name='Kitap',
        ),
        migrations.DeleteModel(
            name='Siir',
        ),
        migrations.DeleteModel(
            name='Yazar',
        ),
    ]
