# Generated by Django 4.1.3 on 2023-04-07 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0026_creator_literatureobject_delete_dergi_delete_kitap_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator',
            name='type',
            field=models.CharField(choices=[('writer', 'Yazar'), ('publisher', 'Yayıncı')], default='writer', max_length=255),
        ),
        migrations.AlterField(
            model_name='literatureobject',
            name='content',
            field=models.TextField(max_length=1000, verbose_name='İçerik'),
        ),
        migrations.AlterField(
            model_name='literatureobject',
            name='creator',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='index.creator', verbose_name='Yazar / Yayıncı'),
        ),
        migrations.AlterField(
            model_name='literatureobject',
            name='image',
            field=models.ImageField(default='foto/noimage.png', upload_to='foto', verbose_name='Fotoğraf'),
        ),
        migrations.AlterField(
            model_name='literatureobject',
            name='name',
            field=models.CharField(max_length=255, verbose_name='İsim'),
        ),
        migrations.AlterField(
            model_name='literatureobject',
            name='type',
            field=models.TextField(choices=[('book', 'Kitap'), ('magazine', 'Dergi'), ('poem', 'Şiir')], verbose_name='Tür'),
        ),
        migrations.AlterField(
            model_name='literatureobject',
            name='url',
            field=models.URLField(verbose_name='Esere ait link'),
        ),
    ]
